<a href="https://colab.research.google.com/github/Pipo0603/ExerciseAI/blob/main/AL_WEEK8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
from sklearn.linear_model import Perceptron #tín hiệu ra là 0 hoặc 1
x=[[0,0],[0,1],[1,0],[1,1]] #cột là 
y=[0,1,1,1] #hàng là số lượng mẫu, số hàng của y và x phải bằng nhau
model=Perceptron()
model.fit(x,y)
model.score(x,y)
x1=[[0.5,0],[0.5,0.1],[0.7,0],[3,5],[1,0.2],[0,0.9]]
y1=model.predict(x1)
print(y1)
model.score(x1,y1)

[0 1 1 1 1 1]


1.0

In [17]:
from sklearn.linear_model import Perceptron
x=[[-0.5,-0.5],[-0.5,0.5],[0.3,-0.5],[-0.1,1]] 
t=[1,1,0,0] 
model=Perceptron()
model.fit(x,t)
model.score(x,t)
x2=[[-62,-25],[0.5,-2],[6,5],[0.3,-7],[5.2,7.4],[0.6,-0.3],[5,-9],[0.6,9.72],[-5.4,-2.3],[21,100]]
y2=model.predict(x2)
print(y2)
model.score(x2,y2)

[1 1 0 1 0 0 0 0 1 0]


1.0

In [28]:
from sklearn  import datasets
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split #tỉ lệ train_test là 7/3 hoặc 8/2. ko đc lấy train đi kiểm tra
from sklearn.metrics import accuracy_score 
from sklearn.preprocessing import StandardScaler #tỉ lệ các giá trị bằng nhau
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
iris=datasets.load_iris()
X=iris.data
y=iris.target
print(X[:5])
print(y[:5])
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3)
sc=StandardScaler()
sc.fit(X_train)
X_train_Std=sc.transform(X_train)
X_test_Std=sc.transform(X_test)
model=Perceptron(max_iter=40, eta0=0.1,random_state=0)#tốc độ eta càng lớn thì sai càng nhiều, thấp thì hội tụ càng chập
model.fit(X_train_Std, y_train)
y_pred=model.predict(X_test_Std)
print(y_pred)
print(y_test)
print('Độ chính xác của mô hình: ',accuracy_score(y_test,y_pred))

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]
[2 1 1 1 2 0 1 1 0 0 2 0 0 2 0 1 2 1 2 1 0 2 2 2 1 2 2 1 1 0 2 1 1 1 0 0 2
 2 1 0 1 1 2 1 1]
[2 1 0 1 2 0 1 1 0 0 2 0 0 2 0 1 2 1 2 1 0 2 2 2 1 2 1 1 1 0 2 1 1 1 0 0 2
 2 1 0 1 2 2 2 1]
Độ chính xác của mô hình:  0.9111111111111111


In [35]:
import pandas as pd
import numpy as np

dataframe = pd.read_csv('/content/crabs.csv')
dataframe.head()
crab_B = dataframe
crab_B.sex = crab_B.sex.apply(lambda x: x.replace("M","1"))
crab_B.sex = crab_B.sex.apply(lambda x: x.replace("F","0"))
print(crab_B)

    speies sex  index  fontallip  rearwidth  length  width  depth
0        B   1      1        8.1        6.7    16.1   19.0    7.0
1        B   1      2        8.8        7.7    18.1   20.8    7.4
2        B   1      3        9.2        7.8    19.0   22.4    7.7
3        B   1      4        9.6        7.9    20.1   23.1    8.2
4        B   1      5        9.8        8.0    20.3   23.0    8.2
..     ...  ..    ...        ...        ...     ...    ...    ...
195      O   0     46       21.4       18.0    41.2   46.2   18.7
196      O   0     47       21.7       17.1    41.7   47.2   19.6
197      O   0     48       21.9       17.2    42.6   47.4   19.5
198      O   0     49       22.5       17.2    43.0   48.7   19.8
199      O   0     50       23.1       20.2    46.2   52.5   21.1

[200 rows x 8 columns]


In [ ]:
x = crab_B.drop(['speies','sex','index'],axis = 1)
print(x)
y = crab_B.sex
print(y)
     

    fontallip  rearwidth  length  width  depth
0         8.1        6.7    16.1   19.0    7.0
1         8.8        7.7    18.1   20.8    7.4
2         9.2        7.8    19.0   22.4    7.7
3         9.6        7.9    20.1   23.1    8.2
4         9.8        8.0    20.3   23.0    8.2
..        ...        ...     ...    ...    ...
95       16.4       14.0    34.2   39.8   15.2
96       16.7       16.1    36.6   41.9   15.4
97       17.4       16.9    38.2   44.1   16.6
98       17.5       16.7    38.6   44.5   17.0
99       19.2       16.5    40.9   47.9   18.1

[100 rows x 5 columns]
0     1
1     1
2     1
3     1
4     1
     ..
95    0
96    0
97    0
98    0
99    0
Name: sex, Length: 100, dtype: object


In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3)
sc = StandardScaler()
sc.fit(x_train)
x_train_std = sc.transform(x_train)
x_test_std = sc.transform(x_test)
model = Perceptron(max_iter = 100, eta0 = 0.1, random_state = 0)
#model: số lần học
model.fit(x_train_std, y_train)
y_pred = model.predict(x_test_std)
print(y_pred)
print(y_test)
print("Độ chính xác của mô hình: ", accuracy_score(y_test, y_pred))

['0' '0' '1' '1' '0' '0' '1' '1' '0' '0' '1' '0' '0' '0' '1' '0' '1' '0'
 '1' '0' '0' '0' '0' '0' '1' '1' '1' '1' '0' '1']
73    0
85    0
48    1
14    1
77    0
74    0
99    0
13    1
2     1
53    0
8     1
78    0
75    0
59    0
31    1
89    0
40    1
52    0
21    1
57    0
56    0
88    0
92    0
83    0
7     1
16    1
29    1
26    1
10    1
43    1
Name: sex, dtype: object
Độ chính xác của mô hình:  0.9


In [43]:
data = pd.read_csv('/content/crabs.csv')
data.head()
crab=data
crab.speies = crab.speies.apply(lambda x: x.replace("B","1"))
crab.speies = crab.speies.apply(lambda x: x.replace("O","0"))
print(crab)
x = crab.drop(['speies','sex','index'],axis = 1)
print(x)
y = crab.speies
print(y)
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3)
sc = StandardScaler()
sc.fit(x_train)
x_train_std = sc.transform(x_train)
x_test_std = sc.transform(x_test)
model = Perceptron(max_iter = 100, eta0 = 0.1, random_state = 0)
#model: số lần học
model.fit(x_train_std, y_train)
y_pred = model.predict(x_test_std)
print(y_pred)
print(y_test)
print("Độ chính xác của mô hình: ", accuracy_score(y_test, y_pred))

    speies sex  index  fontallip  rearwidth  length  width  depth
0        1   M      1        8.1        6.7    16.1   19.0    7.0
1        1   M      2        8.8        7.7    18.1   20.8    7.4
2        1   M      3        9.2        7.8    19.0   22.4    7.7
3        1   M      4        9.6        7.9    20.1   23.1    8.2
4        1   M      5        9.8        8.0    20.3   23.0    8.2
..     ...  ..    ...        ...        ...     ...    ...    ...
195      0   F     46       21.4       18.0    41.2   46.2   18.7
196      0   F     47       21.7       17.1    41.7   47.2   19.6
197      0   F     48       21.9       17.2    42.6   47.4   19.5
198      0   F     49       22.5       17.2    43.0   48.7   19.8
199      0   F     50       23.1       20.2    46.2   52.5   21.1

[200 rows x 8 columns]
     fontallip  rearwidth  length  width  depth
0          8.1        6.7    16.1   19.0    7.0
1          8.8        7.7    18.1   20.8    7.4
2          9.2        7.8    19.0   22.4

NameError: ignored